### ISSUE TITLE
ImportError: libcgns.so.4.4: cannot open shared object file: No such file or directory.

### ISSUE THREAD

**Issue by AFurley** [mdolab/MACH-Aero#150]
## Description

Hello! I am a student in aerospace engineering, and I am attempting to use the MACH-Aero framework to conduct aerodynamic optimization. Unfortunately, upon execution of a simple test file to import pyHyp in the u22-gcc-ompi-latest image, I am running into an error. I am new to Docker (and Python, largely), so I apologize if this is not a bug, but rather a user error. Any help would be appreciated!

### Steps to reproduce issue

1. Pull the u22-gcc-ompi-latest image using Docker and make a container.
2. Attach to the running container in VSCode.
3. In the mdolabuser folder, create and run a python script with the line "from pyhyp import pyHyp".

### Current behavior

![image](https://github.com/mdolab/MACH-Aero/assets/123106633/d6e7eef2-ebec-4802-9486-ad921dc4f20c)

**Comment by eirikurj** [comment]
Hi, your vscode terminal seems to be to set to `sh` (indicated by the `$` prompt), instead of `bash`. This means that none of the MDO Lab environment will be loaded. 
To fix this, you can change the vscode terminal profile to `bash` (and set as default) in vscode terminal window, and that should give you a prompt that looks something like `mdolabuser@2457b3b87661:~$`. From there, you should, be able to run `python` directly, without the absolute path, and import any MDO Lab python package.

**Comment by ewu63** [comment]
Closed due to inactivity.
